spring:
  aop:
    proxy-target-class: true
  profiles:
    active: dev
    base:  com.winway.purchase.controller
    title: "@@project.name@@"
    description: "@@project.description@@"
    version: "@@project.version@@"
    platform: mysql
  datasource:
    name: dev
    url: jdbc:mysql://localhost:3306/213_copy?serverTimezone=UTC&useSSL=false&&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000